name: Release
on:
  workflow_dispatch:
jobs:
  make_github_release:
    uses: datajoint/.github/.github/workflows/make_github_release.yaml@main
  mkdocs_release:
    uses: datajoint/.github/.github/workflows/mkdocs_release.yaml@main
    permissions: 
      contents: write
  devcontainer-build:
    uses: datajoint/.github/.github/workflows/devcontainer-build.yaml@main
  devcontainer-publish:
    needs: 
      - devcontainer-build
    uses: datajoint/.github/.github/workflows/devcontainer-publish.yaml@main
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN_FOR_ELEMENTS}}